name: Build

on:
  push:
    branches:
      - main
    paths:
      - OpenRefine.NET.sln
      - OpenRefine.NET/**
      - OpenRefine.NET.Tests/**

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    env:
      REFINE_VERSION: "3.7.0"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Setup OpenRefine
        run: |
          curl -L -O https://github.com/OpenRefine/OpenRefine/releases/download/${{env.REFINE_VERSION}}/openrefine-linux-${{env.REFINE_VERSION}}.tar.gz
          tar xzf openrefine-linux-${{env.REFINE_VERSION}}.tar.gz
          cd openrefine-${{env.REFINE_VERSION}}
          ./refine &

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal
