name: Publish

on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Setup OpenRefine
        run: |
          curl -L -O https://github.com/OpenRefine/OpenRefine/releases/download/${{env.REFINE_VERSION}}/openrefine-linux-${{env.REFINE_VERSION}}.tar.gz
          tar xzf openrefine-linux-${{env.REFINE_VERSION}}.tar.gz
          cd openrefine-${{env.REFINE_VERSION}}
          ./refine &

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal

      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
          dotnet pack -p:PackageVersion=$PACKAGE_VERSION -c Release

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push **\*.nupkg --no-restore --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
