name: Publish

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  publish:
    env:
      REFINE_VERSION: "3.7.0"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Setup OpenRefine
        run: |
          curl -L -O https://github.com/OpenRefine/OpenRefine/releases/download/${{env.REFINE_VERSION}}/openrefine-linux-${{env.REFINE_VERSION}}.tar.gz
          tar xzf openrefine-linux-${{env.REFINE_VERSION}}.tar.gz
          cd openrefine-${{env.REFINE_VERSION}}
          ./refine &

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack --no-restore -p:PackageVersion=$GITHUB_REF_NAME -c Release

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push **\*.$GITHUB_REF_NAME.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
